### PR TITLE
Add has-photo prop support

### LINKED ISSUE #109: Allow us to provide custom props on findAllAndFilterBySimpleProperties
After https://github.com/nextcloud/server/pull/14389
I need to be able to request the `[NS.NEXTCLOUD, 'has-photo']` prop :)

https://github.com/nextcloud/cdav-library/blob/27c01a47aa007291976a2f8fa861cef8fc6fa075/src/models/addressBook.js#L83-L102

@georgehrke

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #109

### CODE REVIEW

**Comment by skjnldsv** [comment]
:bellhop_bell: :grin:

**Comment by georgehrke** [comment]
@skjnldsv Please squash and build production. Then we can merge. Thx!

**Comment by skjnldsv** [comment]
Sure thing! :vulcan_salute:

**Comment by skjnldsv** [comment]
@georgehrke I guess I should have exposed the property as well so I can access it, right? :roll_eyes: 
https://github.com/nextcloud/cdav-library/blob/18b97d9d45a0fae97648838e09075ec644b18ba6/src/models/vcard.js#L43

**Pull request merged**
