### PR TITLE
Assert build is similar to produced files

### PR DESCRIPTION
**Pull request by tcitworld**
Similar to what we have in server. Can be removed when #400 is done and artefacts removed from repo.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
And it failed :see_no_evil:

**Comment by st3iny** [comment]
I think it failed because we don't rebuild after every dependency update. However, those updates can alter built assets.

We could build once more, amend the changes and merge here but that would break all dependabot PRs in the future. So we have 3 options:
1. Do not merge this PR.
2. Force dependabot to trigger `/compile amend /` on every of his PRs.
3. Make the new workflow optional. It would still indicate PR correctness but we would have to say goodbye to green CI :boom:

**Comment by ChristophWurst** [comment]
sounds like we have less work if we just jump to https://github.com/nextcloud/cdav-library/issues/400

**Comment by st3iny** [comment]
Package will be on npm very soon (ref #600 and #601).

**Pull request closed without merging**
