### PR TITLE
Do not return subscriptions on findAllCalendars()

### PR DESCRIPTION
**Pull request by georgehrke**
Signed-off-by: Georg Ehrke <developer@georgehrke.com>

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Hm, maybe I did something wrong, but on this branch https://github.com/nextcloud/tasks/pull/942 and after `npm install` and `npm run build` I still see subscriptions appearing in the app.

Also, how does the Calendar app load subscriptions? Wouldn't this change also affect it?

**Comment by georgehrke** [comment]
> Also, how does the Calendar app load subscriptions? Wouldn't this change also affect it?

We set a special HTTP Header, so that the server returns Subscription as calendar collections. (so we can fetch cached events from the server)

**Comment by georgehrke** [comment]
> Hm, maybe I did something wrong, but on this branch nextcloud/tasks#942 and after npm install and npm run build I still see subscriptions appearing in the app.

Let me check that right now

**Comment by georgehrke** [comment]
For some mysterious reason, the server is reporting subscriptions as calendars, although it should report them as subscription: https://github.com/sabre-io/dav/blob/master/lib/CalDAV/Subscriptions/Plugin.php#L34

**Comment by georgehrke** [comment]
Ok, now this is embarrassing 🙈
Commit incoming ...

**Comment by georgehrke** [comment]
This should obviously only be done in the calendar, not in cdav: 
https://github.com/nextcloud/cdav-library/pull/272/commits/09207e07b9b072d703a9e7dfd1beafbc22f82f7c

**Comment by georgehrke** [comment]
@raimund-schluessler Please check again

**Comment by raimund-schluessler** [comment]
> 
> 
> @raimund-schluessler Please check again

Subscriptions don't show up anymore 👍

**Pull request merged**
