### PR TITLE
Fix undefined content type

### PR DESCRIPTION
**Pull request by tcitworld**
Thought it would fix https://github.com/nextcloud/calendar/issues/3551 but it doesn't.

Still, wouldn't hurt.

### CODE REVIEW

**Review by st3iny — APPROVED** [review]
LGTM! Updating the package lock has to be done sooner or later anyways. I'd leave it in a separate commit (like it currently is).

**Comment by ChristophWurst** [comment]
conflicts :zipper_mouth_face:

**Comment by osm-frasch** [comment]
Question: Is this issue solved? After upgrading to Nextcloud to 22.2.2, the calendar app no longer loads any appointments. I have had the same problem here since upgrading from NC 21.0.5 to 22.2.2.My calendar app has the version number 2.3.4. However, this only occurs with some employees who use the calendar collaboratively.

**Comment by st3iny** [comment]
I moved the package log upgrade to a separate PR. I didn't change anything else.

**Comment by raimund-schluessler** [comment]
> 
> 
> Thought it would fix [nextcloud/calendar#3551](https://github.com/nextcloud/calendar/issues/3551) but it doesn't.

I reopened https://github.com/nextcloud/calendar/issues/3551 since it got closed automatically.

**Pull request merged**
