### PR TITLE
Rename `master` to `main`

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/cdav-library/issues/602

### CODE REVIEW

**Comment by tcitworld** [comment]
Also in ` .github/workflows/dependabot-approve-merge.yml `

**Review by GretaD — APPROVED** [review]

**Comment by GretaD** [comment]
> Also in `.github/workflows/dependabot-approve-merge.yml`

how do you mean? He did this file

**Review by st3iny — CHANGES_REQUESTED** [review]
https://github.com/nextcloud/cdav-library/blob/25c88b64e2aaeb82c59bf467646d24af9461df57/.github/workflows/build.yml#L7

**Comment by tcitworld** [comment]
@st3iny found the file I was think of :)

**Comment by ChristophWurst** [comment]
Forgot to save the file before the commit :see_no_evil:

**Review by tcitworld — APPROVED** [review]

**Review by st3iny — APPROVED** [review]

**Pull request merged**
