### PR TITLE
Update npm and node engines versions

### PR DESCRIPTION
**Pull request by nextcloud-command**
Automated update of the npm and node engines versions

### CODE REVIEW

**Comment by st3iny** [comment]
Merge after https://github.com/nextcloud/cdav-library/pull/591.

**Review by ChristophWurst — DISMISSED** [review]
I would prefer the non restrictive >=14 unless we know that 15 or later doesn't work

**Comment by st3iny** [comment]
> I would prefer the non restrictive >=14 unless we know that 15 or later doesn't work

Me too. Moreover, v16 is the current LTS (ref https://nodejs.org/en/about/releases/) which also adds to the argument.

**Review by st3iny — APPROVED** [review]
I added the updated package-lock.json. The changes are actually only the node and npm versions. The rest are purely whitespace changes.

We can move on with this, as we support Node 16 by default now.

**Comment by st3iny** [comment]
I rebased to fix conflicts.

**Comment by ChristophWurst** [comment]
Conflicts

**Pull request merged**
